baseURL = "https://amerghazal.github.io/"
languageCode = "en-us"
title = "amerghazal"
theme = "whiteplain"
copyright = "&copy; Copyright 2019 amer ghazal"

[params.author]
  github = "amerghazal"
  
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[[menu.main]]
  name = "Categories"
  identifier = "categories"
  url = "/categories/"
  weight = 1
[[menu.main]]
  name = "Tags"
  identifier = "tags"
  url = "/tags/"
  weight = 2
[[menu.main]]
  name = "Series"
  identifier = "series"
  url = "/series/"
  weight = 3
[[menu.main]]
  name = "Archives"
  identifier = "archives"
  url = "/archives/"
  weight = 4
[[menu.main]]
  name = "About"
  identifier = "about"
  url = "/about/"
  weight = 5


# Footer Menu
[[menu.footer]]
  name = "About"
  weight = 1
  identifier = "about"
  url = "/about/"
